### ISSUE TITLE
Audio feature extraction during preprocessing ？

### ISSUE THREAD

**Issue by zhouyan19** [ictnlp/STEMM#1]
I compare your preprocss procedure (preprocess.sh) to the orginial fairseq example, and find that you remove the step of extracting the audio feature ( as far as my observation is concerned ) . So when you train the fairseq ST baseline, are you using the raw audio inputs  rather than the features as in the original codes ? Or are you using Wav2Vec2.0 to do an audio embedding ?

**Comment by Poeroz** [comment]
Thanks for your question. We use Wav2vec2.0 to encode the raw audio for all experiments.

**Comment by zhouyan19** [comment]
> Thanks for your question. We use Wav2vec2.0 to encode the raw audio for all experiments.

Thanks a lot !
