### ISSUE TITLE
About fine-tuning

### ISSUE THREAD

**Issue by zhouyan19** [ictnlp/STEMM#2]
In the paper, Section 2.2 , you say "We combine those pretrained modules and finetune the whole model for ST". Did you freeze the Wav2Vec2.0 Model during training ? If not , I wonder if it's because of  the mix-up training strategy , so as to bridge the modality gap.

**Comment by Poeroz** [comment]
Thanks for your question. We did not freeze the Wav2vec2.0 module, so that the audio representation can be tuned with training.

**Comment by zhouyan19** [comment]
> Thanks for your question. We did not freeze the Wav2vec2.0 module, so that the audio representation can be tuned with training.

Thank you !
