### ISSUE TITLE
external parallel mt data download.

### ISSUE THREAD

**Issue by zhhao1** [ictnlp/STEMM#3]
## ❓ Questions and Help
Can you provide the download and processing scripts for the additional machine translation data mentioned in the article？The current repository only gives the calculation of bpe. There are many data sources given in the official website, and it is not clear which ones to download. Thank you very much.

**Comment by Poeroz** [comment]
Sorry for my late reply. You can refer to [download-wmt](https://github.com/Glaciohound/Chimera-ST/blob/main/chimera/prepare_data/download-wmt.sh) and [download-opus100](https://github.com/Glaciohound/Chimera-ST/blob/main/chimera/prepare_data/download-opus100.sh) to download the external parallel MT data.
