### ISSUE TITLE
statistical significance of translation results

### ISSUE THREAD

**Issue by zhhao1** [ictnlp/STEMM#4]
## ❓ Questions and Help
In paper, you said "We use sacreBLEU to compute case-sensitive detokenized BLEU scores and the statistical  significance of translation results with paired bootstrap resamplingfor a fair comparison." Is it convenient to realease the code used to calculate the statistical  significance? Sorry for disturbing again.
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Poeroz** [comment]
This is quite easy for sacrebleu >= 2.0.0. You can refer to the [tutorial](https://github.com/mjpost/sacrebleu#multi-system-evaluation) here.

Best regards.
